// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package dbgen

import (
	"context"
	"time"
)

const countEvents = `-- name: CountEvents :one
SELECT COUNT(*) FROM events
`

func (q *Queries) CountEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, car_id, plate_utf8, car_state, sensor_provider_id, event_datetime, capture_timestamp, plate_country, plate_region, plate_confidence, geotag_lat, geotag_lon, vehicle_make, vehicle_model, vehicle_color, camera_serial, camera_ip, raw_json, created_at FROM events WHERE id = ?
`

func (q *Queries) GetEventByID(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CarID,
		&i.PlateUtf8,
		&i.CarState,
		&i.SensorProviderID,
		&i.EventDatetime,
		&i.CaptureTimestamp,
		&i.PlateCountry,
		&i.PlateRegion,
		&i.PlateConfidence,
		&i.GeotagLat,
		&i.GeotagLon,
		&i.VehicleMake,
		&i.VehicleModel,
		&i.VehicleColor,
		&i.CameraSerial,
		&i.CameraIp,
		&i.RawJson,
		&i.CreatedAt,
	)
	return i, err
}

const getImageData = `-- name: GetImageData :one
SELECT image_data FROM images WHERE id = ?
`

func (q *Queries) GetImageData(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getImageData, id)
	var image_data []byte
	err := row.Scan(&image_data)
	return image_data, err
}

const getImagesByEventID = `-- name: GetImagesByEventID :many
SELECT id, image_type, filename, created_at FROM images WHERE event_id = ?
`

type GetImagesByEventIDRow struct {
	ID        int64     `json:"id"`
	ImageType *string   `json:"image_type"`
	Filename  *string   `json:"filename"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetImagesByEventID(ctx context.Context, eventID int64) ([]GetImagesByEventIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getImagesByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetImagesByEventIDRow{}
	for rows.Next() {
		var i GetImagesByEventIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ImageType,
			&i.Filename,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentEvents = `-- name: GetRecentEvents :many
SELECT id, car_id, plate_utf8, car_state, sensor_provider_id, event_datetime, created_at
FROM events
ORDER BY created_at DESC
LIMIT ?
`

type GetRecentEventsRow struct {
	ID               int64     `json:"id"`
	CarID            string    `json:"car_id"`
	PlateUtf8        *string   `json:"plate_utf8"`
	CarState         *string   `json:"car_state"`
	SensorProviderID *string   `json:"sensor_provider_id"`
	EventDatetime    *string   `json:"event_datetime"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) GetRecentEvents(ctx context.Context, limit int64) ([]GetRecentEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentEventsRow{}
	for rows.Next() {
		var i GetRecentEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.CarID,
			&i.PlateUtf8,
			&i.CarState,
			&i.SensorProviderID,
			&i.EventDatetime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (
    car_id, plate_utf8, car_state, sensor_provider_id,
    event_datetime, capture_timestamp, plate_country, plate_region, plate_confidence,
    geotag_lat, geotag_lon, vehicle_make, vehicle_model, vehicle_color,
    camera_serial, camera_ip, raw_json, created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id
`

type InsertEventParams struct {
	CarID            string    `json:"car_id"`
	PlateUtf8        *string   `json:"plate_utf8"`
	CarState         *string   `json:"car_state"`
	SensorProviderID *string   `json:"sensor_provider_id"`
	EventDatetime    *string   `json:"event_datetime"`
	CaptureTimestamp *string   `json:"capture_timestamp"`
	PlateCountry     *string   `json:"plate_country"`
	PlateRegion      *string   `json:"plate_region"`
	PlateConfidence  *float64  `json:"plate_confidence"`
	GeotagLat        *float64  `json:"geotag_lat"`
	GeotagLon        *float64  `json:"geotag_lon"`
	VehicleMake      *string   `json:"vehicle_make"`
	VehicleModel     *string   `json:"vehicle_model"`
	VehicleColor     *string   `json:"vehicle_color"`
	CameraSerial     *string   `json:"camera_serial"`
	CameraIp         *string   `json:"camera_ip"`
	RawJson          *string   `json:"raw_json"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertEvent,
		arg.CarID,
		arg.PlateUtf8,
		arg.CarState,
		arg.SensorProviderID,
		arg.EventDatetime,
		arg.CaptureTimestamp,
		arg.PlateCountry,
		arg.PlateRegion,
		arg.PlateConfidence,
		arg.GeotagLat,
		arg.GeotagLon,
		arg.VehicleMake,
		arg.VehicleModel,
		arg.VehicleColor,
		arg.CameraSerial,
		arg.CameraIp,
		arg.RawJson,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertImage = `-- name: InsertImage :exec
INSERT INTO images (event_id, image_type, filename, image_data, created_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertImageParams struct {
	EventID   int64     `json:"event_id"`
	ImageType *string   `json:"image_type"`
	Filename  *string   `json:"filename"`
	ImageData []byte    `json:"image_data"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) InsertImage(ctx context.Context, arg InsertImageParams) error {
	_, err := q.db.ExecContext(ctx, insertImage,
		arg.EventID,
		arg.ImageType,
		arg.Filename,
		arg.ImageData,
		arg.CreatedAt,
	)
	return err
}

const searchByPlate = `-- name: SearchByPlate :many
SELECT id, car_id, plate_utf8, car_state, sensor_provider_id, event_datetime, created_at
FROM events
WHERE plate_utf8 LIKE ?
ORDER BY created_at DESC
LIMIT ?
`

type SearchByPlateParams struct {
	PlateUtf8 *string `json:"plate_utf8"`
	Limit     int64   `json:"limit"`
}

type SearchByPlateRow struct {
	ID               int64     `json:"id"`
	CarID            string    `json:"car_id"`
	PlateUtf8        *string   `json:"plate_utf8"`
	CarState         *string   `json:"car_state"`
	SensorProviderID *string   `json:"sensor_provider_id"`
	EventDatetime    *string   `json:"event_datetime"`
	CreatedAt        time.Time `json:"created_at"`
}

func (q *Queries) SearchByPlate(ctx context.Context, arg SearchByPlateParams) ([]SearchByPlateRow, error) {
	rows, err := q.db.QueryContext(ctx, searchByPlate, arg.PlateUtf8, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchByPlateRow{}
	for rows.Next() {
		var i SearchByPlateRow
		if err := rows.Scan(
			&i.ID,
			&i.CarID,
			&i.PlateUtf8,
			&i.CarState,
			&i.SensorProviderID,
			&i.EventDatetime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
