// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Archive struct {
	ID         int64     `json:"id"`
	Name       *string   `json:"name"`
	EventCount int64     `json:"event_count"`
	CreatedAt  time.Time `json:"created_at"`
}

type Event struct {
	ID               int64     `json:"id"`
	CarID            string    `json:"car_id"`
	PlateUtf8        *string   `json:"plate_utf8"`
	CarState         *string   `json:"car_state"`
	SensorProviderID *string   `json:"sensor_provider_id"`
	EventDatetime    *string   `json:"event_datetime"`
	CaptureTimestamp *string   `json:"capture_timestamp"`
	PlateCountry     *string   `json:"plate_country"`
	PlateRegion      *string   `json:"plate_region"`
	PlateConfidence  *float64  `json:"plate_confidence"`
	GeotagLat        *float64  `json:"geotag_lat"`
	GeotagLon        *float64  `json:"geotag_lon"`
	VehicleMake      *string   `json:"vehicle_make"`
	VehicleModel     *string   `json:"vehicle_model"`
	VehicleColor     *string   `json:"vehicle_color"`
	CameraSerial     *string   `json:"camera_serial"`
	CameraIp         *string   `json:"camera_ip"`
	RawJson          *string   `json:"raw_json"`
	CreatedAt        time.Time `json:"created_at"`
	ArchiveID        *int64    `json:"archive_id"`
	JsonFilename     *string   `json:"json_filename"`
}

type Image struct {
	ID           int64     `json:"id"`
	EventID      int64     `json:"event_id"`
	ImageType    *string   `json:"image_type"`
	Filename     *string   `json:"filename"`
	ImageData    []byte    `json:"image_data"`
	CreatedAt    time.Time `json:"created_at"`
	DiskFilename *string   `json:"disk_filename"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}
